<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="/_includes/xsl/feeds.xsl" type="text/xsl" media="screen"?>
<rss version="2.0">
	<channel>
		<title><![CDATA[Discovery Academy Album Feed - Class Y supporting Doorway Charity]]></title>
		<link>https://www.thediscoveryacademy.org%2Fdoorwayphotos</link>
		<description><![CDATA[Read the blog post about our work with Doorway
]]></description>
		<generator>Juniper Education Content Management System (CMS) Version: 4.5 (junipereducation.org)</generator>
		<pubDate>Fri, 9 Jun 2017 03:44:37 GMT</pubDate>
		<lastBuildDate>Fri, 9 Jun 2017 03:44:37 GMT</lastBuildDate>
		<item>	<title><![CDATA[ P1020592 ]]></title>	<link>https://www.thediscoveryacademy.org/doorwayphotos&amp;imageid=59</link>	<description><![CDATA[<img src="https://www.thediscoveryacademy.org/_site/data/images/galleries/7/thumb-P1020592.JPG">]]></description>	<pubDate>Fri, 9 Jun 2017 03:44:37 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/doorwayphotos&amp;imageid=59</guid></item><item>	<title><![CDATA[ P1020634 ]]></title>	<link>https://www.thediscoveryacademy.org/doorwayphotos&amp;imageid=60</link>	<description><![CDATA[<img src="https://www.thediscoveryacademy.org/_site/data/images/galleries/7/thumb-P1020634.JPG">]]></description>	<pubDate>Fri, 9 Jun 2017 03:44:37 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/doorwayphotos&amp;imageid=60</guid></item><item>	<title><![CDATA[ P1020636 ]]></title>	<link>https://www.thediscoveryacademy.org/doorwayphotos&amp;imageid=61</link>	<description><![CDATA[<img src="https://www.thediscoveryacademy.org/_site/data/images/galleries/7/thumb-P1020636.JPG">]]></description>	<pubDate>Fri, 9 Jun 2017 03:44:37 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/doorwayphotos&amp;imageid=61</guid></item><item>	<title><![CDATA[ P1020639 ]]></title>	<link>https://www.thediscoveryacademy.org/doorwayphotos&amp;imageid=62</link>	<description><![CDATA[<img src="https://www.thediscoveryacademy.org/_site/data/images/galleries/7/thumb-P1020639.JPG">]]></description>	<pubDate>Fri, 9 Jun 2017 03:44:37 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/doorwayphotos&amp;imageid=62</guid></item><item>	<title><![CDATA[ P1020660 ]]></title>	<link>https://www.thediscoveryacademy.org/doorwayphotos&amp;imageid=63</link>	<description><![CDATA[<img src="https://www.thediscoveryacademy.org/_site/data/images/galleries/7/thumb-P1020660.JPG">]]></description>	<pubDate>Fri, 9 Jun 2017 03:44:37 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/doorwayphotos&amp;imageid=63</guid></item><item>	<title><![CDATA[ P1020662 ]]></title>	<link>https://www.thediscoveryacademy.org/doorwayphotos&amp;imageid=64</link>	<description><![CDATA[<img src="https://www.thediscoveryacademy.org/_site/data/images/galleries/7/thumb-P1020662.JPG">]]></description>	<pubDate>Fri, 9 Jun 2017 03:44:37 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/doorwayphotos&amp;imageid=64</guid></item>
	</channel>
</rss>