<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="/_includes/xsl/feeds.xsl" type="text/xsl" media="screen"?>
<rss version="2.0">
	<channel>
		<title><![CDATA[Discovery Academy Album Feed - Poppy Appeal 2016]]></title>
		<link>https://www.thediscoveryacademy.org%2Fgallery%2F%3Fpid%3D3%26amp%3Bgcatid%3D1%26amp%3Balbumid%3D3</link>
		<description><![CDATA[Class S decorating poppies to raise funds for British Legion Poppy Appeal 2016
]]></description>
		<generator>Juniper Education Content Management System (CMS) Version: 4.5 (junipereducation.org)</generator>
		<pubDate>Mon, 14 Nov 2016 17:13:24 GMT</pubDate>
		<lastBuildDate>Mon, 14 Nov 2016 17:13:24 GMT</lastBuildDate>
		<item>	<title><![CDATA[ WP_20161107_09_43_10_Pro ]]></title>	<link>https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=3&amp;imageid=25</link>	<description><![CDATA[<img src="https://www.thediscoveryacademy.org/_site/data/images/galleries/3/thumb-WP_20161107_09_43_10_Pro.jpg">]]></description>	<pubDate>Mon, 14 Nov 2016 17:13:24 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=3&amp;imageid=25</guid></item><item>	<title><![CDATA[ WP_20161107_12_13_38_Pro ]]></title>	<link>https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=3&amp;imageid=26</link>	<description><![CDATA[<img src="https://www.thediscoveryacademy.org/_site/data/images/galleries/3/thumb-WP_20161107_12_13_38_Pro.jpg">]]></description>	<pubDate>Mon, 14 Nov 2016 17:13:24 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=3&amp;imageid=26</guid></item><item>	<title><![CDATA[ WP_20161107_12_19_59_Pro ]]></title>	<link>https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=3&amp;imageid=27</link>	<description><![CDATA[<img src="https://www.thediscoveryacademy.org/_site/data/images/galleries/3/thumb-WP_20161107_12_19_59_Pro.jpg">]]></description>	<pubDate>Mon, 14 Nov 2016 17:13:24 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=3&amp;imageid=27</guid></item><item>	<title><![CDATA[ WP_20161107_12_20_59_Pro ]]></title>	<link>https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=3&amp;imageid=28</link>	<description><![CDATA[<img src="https://www.thediscoveryacademy.org/_site/data/images/galleries/3/thumb-WP_20161107_12_20_59_Pro.jpg">]]></description>	<pubDate>Mon, 14 Nov 2016 17:13:24 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=3&amp;imageid=28</guid></item><item>	<title><![CDATA[ WP_20161107_12_24_57_Pro ]]></title>	<link>https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=3&amp;imageid=29</link>	<description><![CDATA[<img src="https://www.thediscoveryacademy.org/_site/data/images/galleries/3/thumb-WP_20161107_12_24_57_Pro.jpg">]]></description>	<pubDate>Mon, 14 Nov 2016 17:13:24 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=3&amp;imageid=29</guid></item><item>	<title><![CDATA[ WP_20161107_12_28_02_Pro ]]></title>	<link>https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=3&amp;imageid=30</link>	<description><![CDATA[<img src="https://www.thediscoveryacademy.org/_site/data/images/galleries/3/thumb-WP_20161107_12_28_02_Pro.jpg">]]></description>	<pubDate>Mon, 14 Nov 2016 17:13:24 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=3&amp;imageid=30</guid></item>
	</channel>
</rss>