<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="/_includes/xsl/feeds.xsl" type="text/xsl" media="screen"?>
<rss version="2.0">
	<channel>
		<title><![CDATA[Discovery Academy Album Feed - MacMillan Coffee Event]]></title>
		<link>https://www.thediscoveryacademy.org%2Fgallery%2F%3Fpid%3D3%26amp%3Bgcatid%3D1%26amp%3Balbumid%3D12</link>
		<description><![CDATA[29/09/17
]]></description>
		<generator>Juniper Education Content Management System (CMS) Version: 4.5 (junipereducation.org)</generator>
		<pubDate>Fri, 10 Nov 2017 15:10:21 GMT</pubDate>
		<lastBuildDate>Fri, 10 Nov 2017 15:10:21 GMT</lastBuildDate>
		<item>	<title><![CDATA[ 20170929_140607 ]]></title>	<link>https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=12&amp;imageid=133</link>	<description><![CDATA[<img src="https://www.thediscoveryacademy.org/_site/data/images/galleries/12/thumb-20170929_140607.jpg">]]></description>	<pubDate>Fri, 10 Nov 2017 15:10:21 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=12&amp;imageid=133</guid></item><item>	<title><![CDATA[ 20170929_135948 ]]></title>	<link>https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=12&amp;imageid=131</link>	<description><![CDATA[<img src="https://www.thediscoveryacademy.org/_site/data/images/galleries/12/thumb-20170929_135948.jpg">]]></description>	<pubDate>Fri, 10 Nov 2017 15:10:21 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=12&amp;imageid=131</guid></item><item>	<title><![CDATA[ 3 ]]></title>	<link>https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=12&amp;imageid=209</link>	<description><![CDATA[<img src="https://www.thediscoveryacademy.org/_site/data/images/galleries/12/thumb-3.jpg">]]></description>	<pubDate>Fri, 10 Nov 2017 15:10:21 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=12&amp;imageid=209</guid></item><item>	<title><![CDATA[ 20170929_135958 ]]></title>	<link>https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=12&amp;imageid=210</link>	<description><![CDATA[<img src="https://www.thediscoveryacademy.org/_site/data/images/galleries/12/thumb-20170929_135958.jpg">]]></description>	<pubDate>Fri, 10 Nov 2017 15:10:21 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=12&amp;imageid=210</guid></item><item>	<title><![CDATA[ 1 ]]></title>	<link>https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=12&amp;imageid=211</link>	<description><![CDATA[<img src="https://www.thediscoveryacademy.org/_site/data/images/galleries/12/thumb-1.jpg">]]></description>	<pubDate>Fri, 10 Nov 2017 15:10:21 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/gallery/?pid=3&amp;gcatid=1&amp;albumid=12&amp;imageid=211</guid></item>
	</channel>
</rss>