<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="/_includes/xsl/feeds.xsl" type="text/xsl" media="screen"?>
<rss version="2.0">
	<channel>
		<title><![CDATA[Discovery Academy Page Updates Feed - Curriculum Overview]]></title>
		<link>https://www.thediscoveryacademy.org%2Fcurriculum</link>
		<description><![CDATA[The latest updated pages under Curriculum Overview on the Discovery Academywebsite.]]></description>
		<generator>Juniper Education Content Management System (CMS) Version: 4.5 (junipereducation.org)</generator>
		<pubDate>Thu, 6 Jul 2023 14:38:25 GMT</pubDate>
		<lastBuildDate>Thu, 6 Jul 2023 14:38:25 GMT</lastBuildDate>
		<item>	<title><![CDATA[ SMSC & FBV  - Spiritual, Moral, Cultural & Social Development and Fundamental British Values ]]></title>	<link>https://www.thediscoveryacademy.org/curriculum/values</link>	<description><![CDATA[<p>This page was modified on Thu, 6 Jul 2023 14:38:25 GMT.</p>]]></description>	<pubDate>Thu, 6 Jul 2023 14:38:25 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/curriculum/values</guid></item><item>	<title><![CDATA[ Our Curriculum ]]></title>	<link>https://www.thediscoveryacademy.org/holisticcurriculum</link>	<description><![CDATA[<p>This page was modified on Thu, 6 Jul 2023 14:19:31 GMT.</p>]]></description>	<pubDate>Thu, 6 Jul 2023 14:19:31 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/holisticcurriculum</guid></item><item>	<title><![CDATA[ Physical, Sensory and Personal Care ]]></title>	<link>https://www.thediscoveryacademy.org/page/?title=Physical%2C+Sensory+and+Personal+Care&amp;pid=42</link>	<description><![CDATA[<p>This page was modified on Fri, 26 Mar 2021 10:03:13 GMT.</p>]]></description>	<pubDate>Fri, 26 Mar 2021 10:03:13 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/page/?title=Physical%2C+Sensory+and+Personal+Care&amp;pid=42</guid></item><item>	<title><![CDATA[ Communication and Social Interaction ]]></title>	<link>https://www.thediscoveryacademy.org/page/?title=Communication+and+Social+Interaction&amp;pid=41</link>	<description><![CDATA[<p>This page was modified on Fri, 26 Mar 2021 09:55:30 GMT.</p>]]></description>	<pubDate>Fri, 26 Mar 2021 09:55:30 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/page/?title=Communication+and+Social+Interaction&amp;pid=41</guid></item><item>	<title><![CDATA[ Academic ]]></title>	<link>https://www.thediscoveryacademy.org/academic</link>	<description><![CDATA[<p>This page was modified on Fri, 26 Mar 2021 09:53:12 GMT.</p>]]></description>	<pubDate>Fri, 26 Mar 2021 09:53:12 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/academic</guid></item><item>	<title><![CDATA[ Child Centred Approaches ]]></title>	<link>https://www.thediscoveryacademy.org/childcentredapproaches</link>	<description><![CDATA[<p>This page was modified on Fri, 26 Mar 2021 09:28:37 GMT.</p>]]></description>	<pubDate>Fri, 26 Mar 2021 09:28:37 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/childcentredapproaches</guid></item><item>	<title><![CDATA[ Skills ]]></title>	<link>https://www.thediscoveryacademy.org/page/?title=Skills&amp;pid=43</link>	<description><![CDATA[<p>This page was modified on Mon, 10 Oct 2016 11:13:39 GMT.</p>]]></description>	<pubDate>Mon, 10 Oct 2016 11:13:39 GMT</pubDate>	<guid isPermaLink="true">https://www.thediscoveryacademy.org/page/?title=Skills&amp;pid=43</guid></item>
	</channel>
</rss>

